name: Zig Test and Benchmark

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ZIG_VERSION: 0.14.0-dev.2371+c013f45ad

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, aarch64]
        include:
          - os: ubuntu-latest
            arch: arm
          - os: ubuntu-latest
            arch: riscv64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache Zig
        uses: actions/cache@v3
        with:
          path: ~/zig
          key: ${{ runner.os }}-${{ matrix.arch }}-zig-${{ env.ZIG_VERSION }}

      - name: Install Zig
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          case "${{ runner.os }}-${{ matrix.arch }}" in
            Linux-x86_64)
              wget https://ziglang.org/builds/zig-linux-x86_64-${{ env.ZIG_VERSION }}.tar.xz
              tar -xf zig-linux-x86_64-${{ env.ZIG_VERSION }}.tar.xz
              mv zig-linux-x86_64-${{ env.ZIG_VERSION }} ~/zig
              ;;
            Linux-aarch64)
              wget https://ziglang.org/builds/zig-linux-aarch64-${{ env.ZIG_VERSION }}.tar.xz
              tar -xf zig-linux-aarch64-${{ env.ZIG_VERSION }}.tar.xz
              mv zig-linux-aarch64-${{ env.ZIG_VERSION }} ~/zig
              ;;
            Linux-arm)
              wget https://ziglang.org/builds/zig-linux-armv7a-${{ env.ZIG_VERSION }}.tar.xz
              tar -xf zig-linux-armv7a-${{ env.ZIG_VERSION }}.tar.xz
              mv zig-linux-armv7a-${{ env.ZIG_VERSION }} ~/zig
              ;;
            Linux-riscv64)
              wget https://ziglang.org/builds/zig-linux-riscv64-${{ env.ZIG_VERSION }}.tar.xz
              tar -xf zig-linux-riscv64-${{ env.ZIG_VERSION }}.tar.xz
              mv zig-linux-riscv64-${{ env.ZIG_VERSION }} ~/zig
              ;;
            macOS-x86_64)
              wget https://ziglang.org/builds/zig-macos-x86_64-${{ env.ZIG_VERSION }}.tar.xz
              tar -xf zig-macos-x86_64-${{ env.ZIG_VERSION }}.tar.xz
              mv zig-macos-x86_64-${{ env.ZIG_VERSION }} ~/zig
              ;;
            macOS-aarch64)
              wget https://ziglang.org/builds/zig-macos-aarch64-${{ env.ZIG_VERSION }}.tar.xz
              tar -xf zig-macos-aarch64-${{ env.ZIG_VERSION }}.tar.xz
              mv zig-macos-aarch64-${{ env.ZIG_VERSION }} ~/zig
              ;;
            Windows-x86_64)
              curl -L https://ziglang.org/builds/zig-windows-x86_64-${{ env.ZIG_VERSION }}.zip -o zig.zip
              7z x zig.zip
              mv zig-windows-x86_64-${{ env.ZIG_VERSION }} ~/zig
              ;;
            Windows-aarch64)
              curl -L https://ziglang.org/builds/zig-windows-aarch64-${{ env.ZIG_VERSION }}.zip -o zig.zip
              7z x zig.zip
              mv zig-windows-aarch64-${{ env.ZIG_VERSION }} ~/zig
              ;;
          esac
        shell: bash

      - name: Add Zig to PATH
        run: echo "${HOME}/zig" >> $GITHUB_PATH
        shell: bash

      - name: Cache Zig build artifacts
        uses: actions/cache@v3
        with:
          path: |
            zig-cache
            ~/.cache/zig
          key: ${{ runner.os }}-${{ matrix.arch }}-zig-build-${{ hashFiles('**/*.zig') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-zig-build-

      - name: Formatting
        run: zig fmt --check --color on .

      - name: Unit testing
        run: |
          case "${{ runner.os }}-${{ matrix.arch }}" in
            Linux-x86_64)
              target="x86_64-linux"
              ;;
            Linux-aarch64)
              target="aarch64-linux"
              ;;
            Linux-arm)
              target="arm-linux"
              ;;
            Linux-riscv64)
              target="riscv64-linux"
              ;;
            macOS-x86_64)
              target="x86_64-macos"
              ;;
            macOS-aarch64)
              target="aarch64-macos"
              ;;
            Windows-x86_64)
              target="x86_64-windows"
              ;;
            Windows-aarch64)
              target="aarch64-windows"
              ;;
          esac
          zig build test -Dtarget=$target --summary all

      - name: Building
        run: |
          case "${{ runner.os }}-${{ matrix.arch }}" in
            Linux-x86_64)
              target="x86_64-linux"
              ;;
            Linux-aarch64)
              target="aarch64-linux"
              ;;
            Linux-arm)
              target="arm-linux"
              ;;
            Linux-riscv64)
              target="riscv64-linux"
              ;;
            macOS-x86_64)
              target="x86_64-macos"
              ;;
            macOS-aarch64)
              target="aarch64-macos"
              ;;
            Windows-x86_64)
              target="x86_64-windows"
              ;;
            Windows-aarch64)
              target="aarch64-windows"
              ;;
          esac
          zig build -Dtarget=$target -Doptimize=ReleaseFast